# Generated by Django 4.1.1 on 2022-09-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_project_story_characters_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_reading_mode",
        ),
    ]
