# Generated by Django 4.1.1 on 2022-09-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_project_is_reading_mode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-id"]},
        ),
    ]
